image: Ubuntu1804

stack: node 16

branches:
  only:
    - master

cache: node_modules

install:
  - npm install

build: 

test_script:
  - npm run lint && npm test

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name VV1nc3nt
  - git config --global user.email gormmyz@gmail.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=gh-pages --force --verbose