image: Ubuntu1804

stack: node 16

branches:
  only:
    - master

cache: node_modules

install:
  - npm install

build: 

test_script:
  - npm run lint && npm test

deploy:
  release: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: GITHUB_TOKEN
  artifact: /.*\.nupkg/
  draft: false
  prerelease: false
  on:
    branch: main
    appveyor_repo_tag: